
sonar.projectKey=Saniplagas
sonar.projectName=Saniplagas

sonar.projectVersion=1.0.0
sonar.token=sqp_5f4933e8f610a4512cca9064b96b9120a5001a23
# sonar.sources=src
sonar.exclusions=src/utils/constants/*.js, src/lib/**.*, src/assets/**.*,
src/registerServiceWorker.js, src/**/*.spec.js, src/**/index.js
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
